### ISSUE TITLE
use liac-arff unsuccessfully in python 3.6

### ISSUE THREAD

**Issue by kllzheng** [renatopp/liac-arff#66]
code:

import arff
data=arff.load(open('weather.arff', 'rb'))

error:
Traceback (most recent call last):
  File "c:\Users\yhy\Desktop\test\weather.py", line 6, in <module>
    data=arff.load(open('weather.arff', 'rb'))
  File "C:\Users\yhy\Anaconda3\lib\site-packages\arff.py", line 968, in load
    return_type=return_type)
  File "C:\Users\yhy\Anaconda3\lib\site-packages\arff.py", line 810, in decode
    matrix_type=return_type)
  File "C:\Users\yhy\Anaconda3\lib\site-packages\arff.py", line 724, in _decode
    row = row.strip(' \r\n')
TypeError: a bytes-like object is required, not 'str'

**Comment by mfeurer** [comment]
Could you please try `data=arff.load(open('weather.arff'))`? `rb` opens the file in binary mode, which is not what you want for a text file. If this does not work, please provide a link to the arff file in question.

**Comment by mfeurer** [comment]
Closing this because of inactivity - please reopen if this is still an issue.
